ALTER TABLE CIRCUITS
DROP IF EXISTS CIRCUITREF;
ALTER TABLE CONSTRUCTORS
DROP IF EXISTS CONSTRUCTORREF;
ALTER TABLE DRIVER_STANDINGS
DROP IF EXISTS POSITIONTEXT;
ALTER TABLE DRIVERS
DROP IF EXISTS DRIVERREF;

CREATE TABLE IF NOT EXISTS LOCATION
	AS (SELECT LOCATION, COUNTRY, LAT, LNG, ALT FROM CIRCUITS);
ALTER TABLE LOCATION RENAME COLUMN LOCATION TO CITY;
ALTER TABLE LOCATION ADD COLUMN IF NOT EXISTS LOCATION_ID SERIAL PRIMARY KEY;

ALTER TABLE CIRCUITS
ADD COLUMN IF NOT EXISTS LOCATION_ID INT;
ALTER TABLE CIRCUITS
ADD CONSTRAINT LOCATION_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION (LOCATION_ID);
UPDATE CIRCUITS
SET LOCATION_ID = LOCATION.LOCATION_ID
FROM LOCATION
WHERE CIRCUITS.LOCATION = LOCATION.CITY;

ALTER TABLE circuits
DROP COLUMN IF EXISTS location,
DROP COLUMN IF EXISTS country,
DROP COLUMN IF EXISTS lat,
DROP COLUMN IF EXISTS lng,
DROP COLUMN IF EXISTS alt;

CREATE INDEX DRIVER_STANDINGS_INDEX ON DRIVER_STANDINGS (DRIVERSTANDINGSID);
CREATE INDEX RESULTS_INDEX ON RESULTS (RESULTID);
CREATE INDEX QUALIFYING_INDEX ON QUALIFYING (QUALIFYID);




